# Generated by Django 6.0.5 on 2026-06-02 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SentenceInterpretation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_text",
                    models.TextField(
                        help_text="Texto bruto da sentença colado pelo usuário."
                    ),
                ),
                (
                    "extracted_payload",
                    models.JSONField(
                        default=dict,
                        help_text="DTO do formulário extraído pela LLM (nunca resultado de cálculo).",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        help_text="Identificador do modelo de LLM utilizado.",
                        max_length=128,
                    ),
                ),
                (
                    "confidence_notes",
                    models.TextField(
                        blank=True,
                        help_text="Anotações sobre o grau de confiança na extração.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("extracted", "Extraído"),
                            ("reviewed", "Revisado"),
                            ("discarded", "Descartado"),
                        ],
                        default="extracted",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interpretação de sentença",
                "verbose_name_plural": "Interpretações de sentenças",
                "ordering": ("-created_at",),
            },
        ),
    ]
