# Generated by Django 6.0.5 on 2026-06-02 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("indices", "0003_add_ipca"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "monthly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Taxa mensal (ex.: 0,010000 = 1% a.m.).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("uses_selic", models.BooleanField(default=False)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("fixed_monthly", "Taxa fixa mensal"),
                            ("selic", "SELIC"),
                            ("ipca_plus_capped", "IPCA + taxa, limitado à SELIC"),
                        ],
                        default="fixed_monthly",
                        max_length=32,
                    ),
                ),
                ("legal_basis", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name": "Regra de juros",
                "verbose_name_plural": "Regras de juros",
                "ordering": ("start_date",),
            },
        ),
        migrations.CreateModel(
            name="UnificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("unifies_correction_and_interest", models.BooleanField(default=True)),
                ("legal_basis", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name": "Regra de unificação",
                "verbose_name_plural": "Regras de unificação",
                "ordering": ("start_date",),
            },
        ),
        migrations.CreateModel(
            name="CorrectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("single_index", "Índice único"),
                            ("ipca_plus_capped", "IPCA + taxa, limitado à SELIC"),
                        ],
                        default="single_index",
                        max_length=32,
                    ),
                ),
                (
                    "extra_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Taxa adicional anual (ex.: 0,020000 = 2% a.a.).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("legal_basis", models.CharField(blank=True, max_length=64)),
                (
                    "index_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_rules",
                        to="indices.indextype",
                    ),
                ),
                (
                    "selic_cap_index",
                    models.ForeignKey(
                        blank=True,
                        help_text="Índice usado como teto no modo ipca_plus_capped (geralmente SELIC).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_rule_caps",
                        to="indices.indextype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de correção",
                "verbose_name_plural": "Regras de correção",
                "ordering": ("start_date",),
            },
        ),
    ]
