# Generated by Django 6.0.5 on 2026-06-02 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("indices", "0003_add_ipca"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor base da primeira parcela (ou da única).",
                        max_digits=16,
                    ),
                ),
                ("start_term", models.DateField(help_text="Termo inicial do cálculo.")),
                ("end_term", models.DateField(help_text="Termo final do cálculo.")),
                (
                    "index_selection_mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "Automático")],
                        default="auto",
                        max_length=8,
                    ),
                ),
                (
                    "interest_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Se verdadeiro, juros de mora são aplicados.",
                    ),
                ),
                (
                    "attorney_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentual de honorários (ex.: 10.00 = 10%).",
                        max_digits=5,
                    ),
                ),
                (
                    "installment_mode",
                    models.CharField(
                        choices=[
                            ("single", "Parcela única"),
                            ("multiple", "Múltiplas parcelas"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                (
                    "rpv_issued",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o RPV/Precatório já foi emitido.",
                    ),
                ),
                (
                    "rpv_issue_date",
                    models.DateField(
                        blank=True,
                        help_text="Data de emissão do RPV/Precatório.",
                        null=True,
                    ),
                ),
                (
                    "result_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Rascunho"), ("computed", "Calculado")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "manual_index",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manual_calculations",
                        to="indices.indextype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cálculo",
                "verbose_name_plural": "Cálculos",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CalculationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("installment_order", models.PositiveSmallIntegerField(default=1)),
                ("step_order", models.PositiveSmallIntegerField()),
                ("description", models.TextField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "applied_index",
                    models.CharField(
                        blank=True,
                        help_text="Código do índice aplicado (ex.: INPC, SELIC).",
                        max_length=32,
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Fator acumulado do período.",
                        max_digits=18,
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "base_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor-base deste passo (após etapa anterior).",
                        max_digits=16,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Resultado parcial após este passo.",
                        max_digits=16,
                    ),
                ),
                (
                    "calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="calculations.calculation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa do cálculo",
                "verbose_name_plural": "Etapas do cálculo",
                "ordering": ("calculation", "installment_order", "step_order"),
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor da parcela (ignorado se same_as_first for True).",
                        max_digits=16,
                    ),
                ),
                ("same_as_first", models.BooleanField(default=True)),
                (
                    "calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="calculations.calculation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcela",
                "verbose_name_plural": "Parcelas",
                "ordering": ("calculation", "order"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("calculation", "order"),
                        name="installment_unique_calculation_order",
                    )
                ],
            },
        ),
    ]
