# Generated by Django 6.0.5 on 2026-06-02 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndexType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("IBGE", "IBGE"),
                            ("BCB", "Banco Central"),
                            ("CJF", "Justiça Federal"),
                        ],
                        max_length=8,
                    ),
                ),
                ("sgs_series_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ibge_aggregate", models.CharField(blank=True, max_length=32)),
                ("ibge_variable", models.CharField(blank=True, max_length=32)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo de índice",
                "verbose_name_plural": "Tipos de índice",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="IndexValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_date",
                    models.DateField(
                        help_text="Use o primeiro dia do mês de referência."
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "accumulated_factor",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "index_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="indices.indextype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor do índice",
                "verbose_name_plural": "Valores dos índices",
                "ordering": ("index_type__code", "reference_date"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("index_type", "reference_date"),
                        name="indexvalue_unique_type_date",
                    )
                ],
            },
        ),
    ]
